export const CREATE_RECIPE_ACTION = 'CreateRecipe/CREATE_RECIPE_ACTION';
export const CREATE_RECIPE_SUCCESS_ACTION =
  'CreateRecipe/CREATE_RECIPE_SUCCESS_ACTION';
export const CREATE_RECIPE_FAILURE_ACTION =
  'CreateRecipe/CREATE_RECIPE_FAILURE_ACTION';
