export const GET_PROFILE_ACTION = "Root/GET_PROFILE_ACTION";

export const GET_PROFILE_SUCCESS_ACTION = "Root/GET_PROFILE_SUCCESS_ACTION";

export const GET_PROFILE_FAILURE_ACTION = "Root/GET_PROFILE_FAILURE_ACTION";

export const LOGOUT_ACTION = "Root/LOGOUT";
